title: Kazuki's Docs
description: Documents
theme: just-the-docs

url: https://kazutax.github.io/docs

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/kazutax/docs